export { default as Home } from "./home";
export { default as NoPage } from "./noPage";
export { default as Cliente } from "./cliente/cliente";
export { default as Usuario } from "./usuario";
export { default as Login } from "./login";
export { default as SignUp } from "./signUp";
export { default as Banco } from "./banco";
export { default as Produto } from "./produto/produto";
export { default as CategoriaProduto } from "./categoriaProduto";
// export { default as FormaPgto } from "./formaPgto";
export { default as Compra } from "./compras/compra";
export { default as Venda } from "./venda/venda";
export { default as Testes } from "./teste";
export { default as Template } from "./template";
export { default as Insumo } from "./insumo/insumo";
export { default as Financeiro } from "./financeiro";
export { default as PieMostProduct} from './pieTeste';
